http:
  routers:{% if cookiecutter.frontend_type != 'none' %}{% if cookiecutter.backend_type != 'none' %}
    {{ cookiecutter.backend_service_slug }}:
      rule: |
        PathPrefix(`/__debug__`) ||
        PathPrefix(`/admin`) ||
        PathPrefix(`/api`) ||{% if cookiecutter.media_storage == 'local' %}
        PathPrefix(`/media`) ||{% endif %}
        PathPrefix(`/static`)
      service: {{ cookiecutter.backend_service_slug }}{% endif %}
    {{ cookiecutter.frontend_service_slug }}:
      rule: PathPrefix(`/`)
      service: {{ cookiecutter.frontend_service_slug }}{% else %}
    {{ cookiecutter.backend_service_slug }}:
      rule: PathPrefix(`/`)
      service: {{ cookiecutter.backend_service_slug }}{% endif %}
  services:{% if cookiecutter.backend_type != 'none' %}
    {{ cookiecutter.backend_service_slug }}:
      loadBalancer:
        servers:
          - url: "http://{{ cookiecutter.backend_service_slug }}:8000/"{% endif %}{% if cookiecutter.frontend_type != 'none' %}
    {{ cookiecutter.frontend_service_slug }}:
      loadBalancer:
        servers:
          - url: "http://{{ cookiecutter.frontend_service_slug }}:3000/"{% endif %}

tls:
  certificates:
    - certFile: /traefik/localhost/cert.pem
      keyFile: /traefik/localhost/key.pem
