os: linux
dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - isort --check-only --recursive
  - flake8
  - pytest

after_success:
  - codecov
