[tool.black]
target-version = ["py311"]

[tool.isort]
atomic = true
profile = "black"

[tool.mypy]
ignore_missing_imports = true
python_version = "3.11"

[tool.coverage.html]
title = "Talos - Coverage"
show_contexts = true

[tool.coverage.report]
show_missing = true

[tool.coverage.run]
branch = true
dynamic_context = "test_function"
concurrency = ["multiprocessing"]
data_file = ".coverages/.coverage"
disable_warnings = ["no-data-collected"]
omit = [
    ".venv/*",
    "venv/*",
]
source = ["."]

[tool.ruff]
 extend-exclude = [
     "__pycache__",
     ".vscode*",
 ]
 extend-ignore = [
    "D203",
    "D212",
    "D213",
    "D214",
    "D215",
    "D404",
    "D405",
    "D406",
    "D407",
    "D408",
    "D409",
    "D410",
    "D411",
    "D413",
    "D415",
    "D416",
    "D417",
    "E501",
 ]
 select = ["B", "C", "D", "E", "F", "I", "W", "B9"]
 target-version = "py311"

 [tool.ruff.isort]
 known-first-party = [
     "bootstrap",
 ]
