loki:
  config:
    schema_config:
      configs:
        - from: "2020-10-24"
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: aws
      aws:
        s3forcepathstyle: true
