## Loki stack
## https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-observability/assets/manifests/loki-stack-values-v2.6.4.yaml

loki:
  enabled: true
  config:
    chunk_store_config:
        max_look_back_period: "4400h"
    table_manager:
        retention_deletes_enabled: true
        retention_period: "4400h"
    limits_config:
        max_query_length: "2200h"

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
