api:
  debug: true

entryPoints:
  websecure:
    address: ":8443"
    http:
      tls:
        options:

log:
  level: INFO

ping: true

providers:
  file:
    filename: /traefik/config/dynamic.yaml
