apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: {{cookiecutter.project_slug}}-production{% if cookiecutter.use_media == "Yes" %}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m{% endif %}
spec:
  rules:
    - host: www.{{cookiecutter.domain_url}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {% if cookiecutter.which_frontend in ["React", "React (TypeScript)"] %}frontend-cluster-ip-service
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: backend-cluster-ip-service
                port:
                  number: 8000
          - path: /admin/
            pathType: Prefix
            backend:
              service:
                name: backend-cluster-ip-service
                port:
                  number: 8000
          - path: /static/
            pathType: Prefix
            backend:
              service:
                name: {% endif %}backend-cluster-ip-service
                port:
                  number: 8000
