apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgresql-dump-cron
  namespace: {{cookiecutter.project_slug}}-production
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          containers:
            - name: postgresql-dump-to-s3
              image: registry.gitlab.com/deliverytools/pg-dump-restore-to-from-s3:latest
              env:
                # backend
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: DATABASE_URL
                - name: DJANGO_CONFIGURATION
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: DJANGO_CONFIGURATION
                # s3
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_STORAGE_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_STORAGE_BUCKET_NAME
                - name: AWS_S3_HOST
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_S3_HOST
                - name: AWS_S3_BACKUP_PATH
                  value: "$(DJANGO_CONFIGURATION)/backup"
              args:
                - /pg_dump_to_s3.sh
          restartPolicy: OnFailure
