apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-persistent-volume-claim
  namespace: {{cookiecutter.project_slug}}-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
