apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup-cron
  namespace: {{cookiecutter.project_slug}}-production
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          volumes:
            - name: postgres-backup-storage
              persistentVolumeClaim:
                claimName: postgres-backup-persistent-volume-claim
          containers:
          - name: postgres-backup-script
            image: registry.gitlab.com/deliverytools/postgresqlbackup:latest
            volumeMounts:
              - name: postgres-backup-storage
                mountPath: /backup
            env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
            - name: PGHOST
              value: "postgres-cluster-ip-service"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            args:
            - ./pg_dump.sh
            - {{cookiecutter.project_slug}}
          restartPolicy: OnFailure
