version: "3.4"

services:
{% if cookiecutter.backend_type != "none" %}
  {{ cookiecutter.backend_type }}:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./{{ cookiecutter.backend_type }}
      target: ${BACKEND_BUILD_TARGET:-local}
    depends_on:
      - postgres
    environment:
      - CACHE_URL
      - DATABASE_URL
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CONFIGURATION
      - DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL
      - DJANGO_SESSION_COOKIE_DOMAIN
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - EMAIL_URL
      - PYTHONBREAKPOINT
    user: ${USER:-appuser}
    volumes:
      - ./backend:/app{% endif %}
{% if cookiecutter.frontend_type != "none" %}
  {{ cookiecutter.frontend_type }}:
    build:
      context: ./{{ cookiecutter.frontend_type }}
      dockerfile: docker/local.Dockerfile{% if cookiecutter.backend_type != "none" %}
    depends_on:
      - {{ cookiecutter.backend_type }}{% endif %}
    environment:
      - INTERNAL_API_URL
      - NEXT_PUBLIC_API_URL=${API_URL}
      - NODE_ENV
      - REACT_ENVIRONMENT=${DJANGO_CONFIGURATION}
    volumes:
      - ./frontend:/app{% endif %}

  nginx:
    build: ./nginx{% if cookiecutter.backend_type != 'none' or cookiecutter.frontend_type != 'none' %}
    depends_on:{% if cookiecutter.backend_type != 'none' %}
      - {{ cookiecutter.backend_type }}{% endif %}{% if cookiecutter.backend_type != 'none' %}
      - {{ cookiecutter.frontend_type }}{% endif %}{% endif %}
    ports:
      - ${LOCAL_HTTP_PORT:-8080}:80
      - ${LOCAL_HTTPS_PORT:-8443}:443

  postgres:
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    image: postgres:13-buster
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
