version: "3.4"

services:
{% if cookiecutter.backend_type != "none" %}
  {{ cookiecutter.backend_service_slug }}:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./{{ cookiecutter.backend_service_slug }}
      target: ${BACKEND_BUILD_TARGET:-local}
    depends_on:
      - postgres
    environment:
      - CACHE_URL
      - DATABASE_URL
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CONFIGURATION
      - DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL
      - DJANGO_SESSION_COOKIE_DOMAIN
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - EMAIL_URL
      - PYTHONBREAKPOINT
    user: ${USER:-appuser}
    volumes:
      - ./{{ cookiecutter.backend_service_slug }}:/app{% endif %}
{% if cookiecutter.frontend_type != "none" %}
  {{ cookiecutter.frontend_service_slug }}:
    build:
      context: ./{{ cookiecutter.frontend_service_slug }}
      dockerfile: docker/local.Dockerfile{% if cookiecutter.backend_type != "none" %}
    depends_on:
      - {{ cookiecutter.backend_service_slug }}{% endif %}
    environment:
      - INTERNAL_BACKEND_URL=${INTERNAL_BACKEND_URL:-http://{{ cookiecutter.backend_service_slug }}:{{ cookiecutter.backend_service_port }}{{ '}' }}
      - NEXT_PUBLIC_PROJECT_URL=${PROJECT_URL:-https://localhost:8443}
      - REACT_ENVIRONMENT=${REACT_ENVIRONMENT:-Development}
    volumes:
      - ./{{ cookiecutter.frontend_service_slug }}:/app{% endif %}

  nginx:
    build: ./nginx{% if cookiecutter.backend_type != 'none' or cookiecutter.frontend_type != 'none' %}
    depends_on:{% if cookiecutter.backend_type != 'none' %}
      - {{ cookiecutter.backend_service_slug }}{% endif %}{% if cookiecutter.backend_type != 'none' %}
      - {{ cookiecutter.frontend_service_slug }}{% endif %}{% endif %}
    ports:
      - ${LOCAL_HTTP_PORT:-8080}:80
      - ${LOCAL_HTTPS_PORT:-8443}:443

  postgres:
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    image: postgres:13-buster
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
