version: "3.8"

services:
{% if cookiecutter.backend_type != "none" %}
  {{ cookiecutter.backend_service_slug }}:
    build:
      args:
        USER: ${USER:-appuser}
      context: ./{{ cookiecutter.backend_service_slug }}
      target: ${BACKEND_BUILD_TARGET:-local}
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CACHE_URL
      - DATABASE_URL
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_CONFIGURATION
      - DJANGO_DEBUG
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_SECRET_KEY
      - DJANGO_SERVER_EMAIL
      - DJANGO_SESSION_COOKIE_DOMAIN
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - EMAIL_URL{% if cookiecutter.use_pact == "true" %}
      - PACT_BROKER_URL
      - PACT_PROVIDER_NAME{% endif %}
      - PYTHONBREAKPOINT
      - PYTHONDEVMODE
      - PYTHONTRACEMALLOC
    healthcheck:
      test: curl --fail --head http://backend:8000/{{ cookiecutter.backend_service_slug }}/health/ || exit 1
      interval: 30s
      start_period: 5s
      timeout: 5s
      retries: 5
    user: ${USER:-appuser}
    volumes:
      - ./{{ cookiecutter.backend_service_slug }}:/app{% endif %}
{% if cookiecutter.frontend_type != "none" %}
  {{ cookiecutter.frontend_service_slug }}:
    build:
      args:
        GROUP_ID: ${GROUP_ID:-1000}
        USER_ID: ${USER_ID:-1000}
        USER: ${USER:-appuser}
      context: ./{{ cookiecutter.frontend_service_slug }}
      dockerfile: ${FRONTEND_DOCKER_FILE:-docker/local.Dockerfile}{% if cookiecutter.backend_type != "none" %}
    healthcheck:
      test: wget -O- -q http://localhost:3000/{{ cookiecutter.frontend_service_slug }}/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 5s
      retries: 5
    environment:
      - INTERNAL_BACKEND_URL=${INTERNAL_BACKEND_URL:-http://{{ cookiecutter.backend_service_slug }}:{{ cookiecutter.backend_service_port }}{{ '}' }}
      - NEXT_PUBLIC_PROJECT_URL=${PROJECT_URL:-https://localhost:8443}
      - REACT_ENVIRONMENT=${REACT_ENVIRONMENT:-Development}
    user: ${USER:-appuser}
    volumes:
      - ./{{ cookiecutter.frontend_service_slug }}:/app
      - /app/node_modules{% endif %}

  traefik:
    command:
      - "--configFile=/traefik/conf/static.yaml"
    depends_on:{% if cookiecutter.backend_type != 'none' %}
      {{ cookiecutter.backend_service_slug }}:
        condition: service_started{% endif %}{% if cookiecutter.frontend_type != 'none' %}
      {{ cookiecutter.frontend_service_slug }}:
        condition: service_healthy{% endif %}
    healthcheck:
      test: ["CMD", "traefik" ,"healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      start_period: 5s
      retries: 5
    image: traefik:v2.10
    ports:
      - "${LOCAL_HTTPS_PORT:-8443}:8443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    volumes:
      - ./traefik/:/traefik/:ro

  postgres:
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_INITDB_ARGS=--no-sync
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      timeout: 3s
      retries: 30
    image: postgres:14-bullseye
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
