# Custom values for Traefik
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

logs:
  general:
    level: "INFO"
  access:
    enabled: true

providers:
  kubernetesIngress:
    enabled: true
    ingressClass: "traefik-cert-manager"
  kubernetesIngressRoute:
    enabled: true
