## Grafana Helm Chart
## https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml

## DO K8s Starter Kit
## https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/blob/main/04-setup-observability/assets/manifests/prom-stack-values-v35.5.1.yaml

persistence:
  storageClassName: do-block-storage
  accessModes: ["ReadWriteOnce"]
  size: 5Gi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
          foldersFromFilesStructure: true

dashboardsConfigMaps:
  default: grafana-k8s-logs-dashboard
