api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  websecure:
    address: ":8443"
    http:
      tls:
        options: 

log:
  level: ERROR

http:
  routers:
    {{ cookiecutter.backend_service_slug }}:
      rule: "PathPrefix(`/admin`)" 
      service: {{ cookiecutter.backend_service_slug }}
    {{ cookiecutter.backend_service_slug }}-static:
      rule: "PathPrefix(`/static`)" 
      service: {{ cookiecutter.backend_service_slug }}
    {{ cookiecutter.backend_service_slug }}-api:
      rule: "PathPrefix(`/api`)" 
      service: {{ cookiecutter.backend_service_slug }}
    {{ cookiecutter.backend_service_slug }}-debug:
      rule: "PathPrefix(`/__debug__`)" 
      service: {{ cookiecutter.backend_service_slug }}
    {{ cookiecutter.frontend_service_slug }}:
      rule: "PathPrefix(`/`)" 
      service: {{ cookiecutter.frontend_service_slug }}
    {{ cookiecutter.frontend_service_slug }}-sockjs-node:
      rule: "PathPrefix(`/sockjs-node`)" 
      service: {{ cookiecutter.frontend_service_slug }}

  services:
    {{ cookiecutter.backend_service_slug }}:
      loadBalancer:
        servers:
        - url: "http://{{ cookiecutter.backend_service_slug }}:8000/"
    {{ cookiecutter.frontend_service_slug }}:
      loadBalancer:
        servers:
        - url: "http://{{ cookiecutter.frontend_service_slug }}:3000/"

providers:
  file: 
    filename: /traefik/config.yaml

tls:
  certificates:
    - certFile: /traefik/localhost/cert.pem
      keyFile: /traefik/localhost/key.pem
